options(warn = -1) # suppress all warning messages generated by R


header = dashboardHeader(title = "Exploring the IMDB_Moveis ", titleWidth = 500)

sidebar = dashboardSidebar(disable = T)

body = dashboardBody(
  
  tabBox(id = "tabs", height = NULL , width = 12,
         
         tabPanel( id="tab1", 
                   title = strong("Tab 1"), status = "primary",
                   height = NULL , width = 12,
                   fluidRow(box(
                     column(6,
                     selectInput(inputId="genres", label="Genres:", choices=unique(imdb$genres), selected="Action|Thriller")),
                     column(6,
                     selectInput(inputId="language",label="Language:", choices=unique(imdb$language), selected="English")),
                     ),
                     box(
                       column(12,
                              dataTableOutput("share")),
                     ),
                     fluidRow(box(width = 12,
                       column(6,plotOutput("bubble")),
                       column(6,plotOutput("bar"))
                     )),
                     box(
                       tabPanel(id="tabss",
                                title = "Summary of the data",
                                fluidPage(
                                  verbatimTextOutput("sum")
                                )
                       )
                     )
                   
                     
                   ),
                   
                         
         )
  )
)  

dashboardPage(header, sidebar, body, skin = "purple", title = "Exploring the IMDB_Moveis data with R Shiny Dashboard")
